### ISSUE TITLE
关于类解析的实现，可以参考的另一种风格

### ISSUE THREAD

**Issue by duangsuse** [tzh476/zvm#2]
> https://github.com/tzh476/zvm/blob/master/src/main/java/com/zvm/classfile/ClassFile.java#L129

suse 写过一个类似的实现，能够解析常量池。

https://github.com/duangsuse-valid-projects/SomeAXML/blob/master/src/commonTest/kotlin/org/duangsuse/bin/pat/JavaClass.kt#L42

SomeAXML 其实应当叫 `org.duangsuse.bin`，目前还没有包装也没算结束，路过顺便支持一下。 :wink: 

其它部分没看，只特意看了类字节解析部分，有点好奇一个指令一个类…… 会不会有点过度分离了，用的是内部类吗？如果是静态方法还是一类指令一个类吧。

**Comment by duangsuse** [comment]
注：上面引用的实现是参照《Java虚拟机高级特性与最佳实践》第二版编写的，所以相关术语比较刻板。
因为只是作为测试所以没定义完，但仅仅这些代码已经完成了一个可以修改类文件常量池的应用库了，参考 [这个](https://github.com/duangsuse-valid-projects/SomeAXML/blob/master/src/commonTest/kotlin/org/duangsuse/bin/pat/AbstractJavaClassTests.kt#L12) Kotlin Common 测试。

**Comment by tzh476** [comment]
多谢大神的建议。找到了常量池的共性，很好的参考，值得学习！
指令的话现在是一个指令一个类，后面可以优化成一类指令一个类～
